### ISSUE TITLE
Support for multiple spritesheets

### ISSUE THREAD

**Issue by ened** [CodeAndWeb/uikit-sprite-sheet-example#1]
Great software, thank you!
Is there a possibility to load multiple sprite sheets at once?
I will have about 15 sprite sheets per "animation" and look for a way to load the efficiently.
Perhaps an additional "spritesWithContentOfFile" method called "spritesWithContentsOfFiles:(NSArray*)"?

**Comment by AREEJ-QURAAN** [comment]
Hi all 
please i also faced the same issue , i can't deal with one single animation that has many sprite sheets please i just need to understand how to run one animation with say X sprite sheets and X textures 
thanks
